[env]
DCW_SOY_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
bun = { version = '1.3.6' }
node = { version = '25.2.1' }

[tasks]
'claude' = { run = "bun x @anthropic-ai/claude-code", description = "Invoke Claude Code", alias = "cc" }
